# $NetBSD$

DISTNAME=	agm-1.3.1
CATEGORIES=	local
MASTER_SITES=	ftp://ftp.ibiblio.org/pub/linux/games/amusements/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE
HOMEPAGE=	ftp://ftp.ibiblio.org/pub/linux/games/amusements/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

.include "../../mk/bsd.pkg.mk"
