# $NetBSD: Makefile,v 1.7 2016/07/09 13:03:43 wiz Exp $

.include "../../local/protobuf/Makefile.common"

DISTNAME=	protobuf-java-3.0.0
PKGNAME=	java-${DISTNAME:S/-java//}
CATEGORIES+=	java

MAINTAINER=	khorben@defora.org
COMMENT=	Java bindings for protobuf

.include "../../local/protobuf/buildlink3.mk"
#.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
