# $NetBSD$

DISTNAME=	nvidia-texture-tools-2.0.8
CATEGORIES=	graphics
MASTER_SITES=	${MASTER_SITE_GITHUB:=castano/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/castano/nvidia-texture-tools/wiki
COMMENT=	Texture processing tools with support for Direct3D 10 and 11 formats
LICENSE=	mit

HAS_CONFIGURE=	yes
USE_CMAKE=	yes
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
