# $NetBSD$

DISTNAME=	fsmon-1.4
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_GITHUB:=nowsecure/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/nowsecure/fsmon/
COMMENT=	Monitor filesystem
LICENSE=	mit

USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
