# $NetBSD$

DISTNAME=	vunit-0.69.0
CATEGORIES=	cad
MASTER_SITES=	${MASTER_SITE_GITHUB:=VUnit/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://vunit.github.io/
COMMENT=	Unit testing framework for VHDL/SystemVerilog
LICENSE=	mpl-2.0 AND artistic-2.0

#USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
