# $NetBSD$

DISTNAME=	tuxkart-0.4.0
CATEGORIES=	games
MASTER_SITES=	http://tuxkart.sourceforge.net/dist/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://tuxkart.sourceforge.net/dist/
COMMENT=	Racing game starring Tux
LICENSE=	gnu-gpl-v2

GNU_CONFIGURE=	yes
USE_LANGUAGES=	c c++

.include "../../games/plib/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
