# $NetBSD$

DISTNAME=	atanks-6.4
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=atanks/}
#https://sourceforge.net/projects/atanks/files/atanks/atanks-6.4/atanks-6.4.tar.gz/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://atanks.sourceforge.net/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
