# $NetBSD$

DISTNAME=	lbstanza-0.8.22
CATEGORIES=	lang
MASTER_SITES=	${MASTER_SITE_GITHUB:=StanzaOrg/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://lbstanza.org/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=	${WRKDIR}/lbstanza-0.8.22

.include "../../mk/bsd.pkg.mk"
