# $NetBSD: Makefile.common,v 1.2 2015/06/10 09:02:06 wiedi Exp $
#
# used by devel/protobuf/Makefile
# used by devel/py-protobuf/Makefile

MASTER_SITES=	${MASTER_SITE_GITHUB:=google/}
GITHUB_PROJECT=	protobuf
GITHUB_RELEASE=	v${PKGVERSION_NOREV}

CATEGORIES=	devel
HOMEPAGE=       http://code.google.com/p/protobuf/

LICENSE=	modified-bsd

PATCHDIR=	${.CURDIR}/../../local/protobuf/patches
