# $NetBSD$

PKGNAME=	py-hippyvm

GIT_REPOSITORIES=	hippyvm
GIT_REPO.hippyvm=	git@github.com:hippyvm/hippyvm.git

#GITHUB_PROJECT=	hippyvm
#DISTNAME=	ecoop16_artefact_0_1
#PKGNAME=	${GITHUB_PROJECT}-${DISTNAME}
CATEGORIES=	lang
#MASTER_SITES=	${MASTER_SITE_GITHUB:=hippyvm/}
#EXTRACT_SUFX=	.zip
#DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE
HOMEPAGE=	https://github.com/hippyvm/hippyvm/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

#WRKSRC=	${WRKDIR}/hippyvm-ecoop16_artefact_0_1

.include "../../wip/mk/git-package.mk"
.include "../../mk/bsd.pkg.mk"
