# $NetBSD$

DISTNAME=	limitload-0.20
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_GITHUB:=stelic/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/stelic/limitload/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
