# $NetBSD$

DISTNAME=	brlcad-7.24.2
CATEGORIES=	cad
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=brlcad/}
# https://sourceforge.net/projects/brlcad/files/BRL-CAD%20Source/7.24.2/brlcad-7.24.2.tar.gz/download

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://brlcad.org/
COMMENT=	Open source cross-platform solid modeling system
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
