# $NetBSD$

DISTNAME=	Veriwell-2.8.7
CATEGORIES=	cad
MASTER_SITES=	https://sourceforge.net/projects/veriwell/files/VeriWell/Veriwell%202.8.7/
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=VeriWell/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE
HOMEPAGE=	https://sourceforge.net/projects/veriwell/files/VeriWell/Veriwell%202.8.7/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GNU_CONFIGURE=	yes
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
