# $NetBSD$

DISTNAME=	0ad-0.0.20-alpha-unix-data
CATEGORIES=	local
MASTER_SITES=	http://releases.wildfiregames.com/
EXTRACT_SUFX=	.tar.xz

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE
HOMEPAGE=	http://releases.wildfiregames.com/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/0ad-0.0.20-alpha
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
