# $NetBSD$

DISTNAME=	accelerator-0.1.1
CATEGORIES=	games
MASTER_SITES=	https://sourceforge.net/projects/accelerator3d/files/accelerator/0.1.1/
EXTRACT_SUFX=	.zip

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://sourceforge.net/projects/accelerator3d/files/accelerator/0.1.1/
COMMENT=	Fast-paced, 3D, first-person shoot/dodge-'em-up
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/accelerator
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
