# $NetBSD$

GITHUB_PROJECT=	USD
DISTNAME=	USD-0.7.1
PKGNAME=	${DISTNAME:tl}
CATEGORIES=	multimedia
MASTER_SITES=	${MASTER_SITE_GITHUB:=PixarAnimationStudios/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

# https://github.com/PixarAnimationStudios/USD/archive/v0.7.1.zip

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE
HOMEPAGE=	https://github.com/PixarAnimationStudios/USD/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/USD-0.7.1
USE_CMAKE=	yes
USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
