# $NetBSD$

DISTNAME=	rt-tests-1.0
CATEGORIES=	local
MASTER_SITES=	https://www.kernel.org/pub/linux/utils/rt-tests/
EXTRACT_SUFX=	.tar.xz

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE
HOMEPAGE=	https://www.kernel.org/pub/linux/utils/rt-tests/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_TOOLS+=	gmake

MAKE_FLAGS+=	NUMA=0

.include "../../mk/bsd.pkg.mk"
