# $NetBSD$

DISTNAME=	wrogue-0.8.0b
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_GENTOO:=distfiles/}
EXTRACT_SUFX=	.zip

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://freecode.com/projects/wrogue/
COMMENT=	Dark science fantasy roguelike game
LICENSE=	gnu-gpl-v3

.include "../../mk/bsd.pkg.mk"
