# $NetBSD$

DISTNAME=	reptyr-0.6.2
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_GITHUB:=nelhage/}
GITHUB_TAG=	${PKGNAME_NOREV}
EXTRACT_SUFX=	.zip

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/nelhage/reptyr/
COMMENT=	Reparent a running program to a new terminal 
LICENSE=	mit

USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
